### ISSUE TITLE
运行过程中 java.lang.NoClassDefFoundError: 

### ISSUE THREAD

**Issue by dongfucai** [caoym/jjvm#2]
load class is exist 
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/org/apache/bcel/internal/Constants
        at org.caoym.jjvm.opcode.BytecodeInterpreter.parseCodes(BytecodeInterpreter.java:58)
        at org.caoym.jjvm.opcode.JvmOpcodeMethod.<init>(JvmOpcodeMethod.java:24)
        at org.caoym.jjvm.opcode.JvmOpcodeClass.<init>(JvmOpcodeClass.java:49)
        at org.caoym.jjvm.opcode.JvmOpcodeClass.read(JvmOpcodeClass.java:30)
        at org.caoym.jjvm.JvmDefaultClassLoader.loadClass(JvmDefaultClassLoader.java:37)
        at org.caoym.jjvm.VirtualMachine.getClass(VirtualMachine.java:50)
        at org.caoym.jjvm.VirtualMachine.run(VirtualMachine.java:38)
        at org.caoym.jjvm.JJvm.main(JJvm.java:25)
Caused by: java.lang.ClassNotFoundException: com.sun.o

**Comment by dongfucai** [comment]
运行过程中包了 一个这样的错误
