### ISSUE TITLE
java.lang.NoSuchMethodException: <init>:(Ljava/lang/String;)V not exist

### ISSUE THREAD

**Issue by dongfucai** [caoym/jjvm#3]
> org/caoym/jjvm/Main.<clinit>@0:NEW

 java.lang.NoSuchMethodException: <init>:(Ljava/lang/String;)V not exist
	at org.caoym.jjvm.natives.JvmNativeClass.getMethod(JvmNativeClass.java:52)
	at org.caoym.jjvm.opcode.OpcodeRout$7.invoke(OpcodeRout.java:95)
	at org.caoym.jjvm.opcode.BytecodeInterpreter$1.invoke(BytecodeInterpreter.java:63)
	at org.caoym.jjvm.opcode.BytecodeInterpreter.run(BytecodeInterpreter.java:49)
	at org.caoym.jjvm.opcode.JvmOpcodeMethod.call(JvmOpcodeMethod.java:63)
	at org.caoym.jjvm.opcode.JvmOpcodeClass.clinit(JvmOpcodeClass.java:87)
	at org.caoym.jjvm.opcode.JvmOpcodeMethod.call(JvmOpcodeMethod.java:62)
	at org.caoym.jjvm.VirtualMachine.run(VirtualMachine.java:44)
	at org.caoym.jjvm.JJvm.main(JJvm.java:28)

> org/caoym/jjvm/Main.<clinit>@1:DUP
> org/caoym/jjvm/Main.<clinit>@2:LDC
> org/caoym/jjvm/Main.<clinit>@3:INVOKESPECIAL

**Comment by dongfucai** [comment]
> org/caoym/jjvm/Main.<clinit>@0:NEW
> org/caoym/jjvm/Main.<clinit>@1:DUP
> org/caoym/jjvm/Main.<clinit>@2:LDC
> org/caoym/jjvm/Main.<clinit>@3:INVOKESPECIAL
java.lang.NoSuchMethodException: <init>:(Ljava/lang/String;)V not exist
	at org.caoym.jjvm.natives.JvmNativeClass.getMethod(JvmNativeClass.java:52)
	at org.caoym.jjvm.opcode.OpcodeRout$7.invoke(OpcodeRout.java:95)
	at org.caoym.jjvm.opcode.BytecodeInterpreter$1.invoke(BytecodeInterpreter.java:63)
	at org.caoym.jjvm.opcode.BytecodeInterpreter.run(BytecodeInterpreter.java:49)
	at org.caoym.jjvm.opcode.JvmOpcodeMethod.call(JvmOpcodeMethod.java:63)
	at org.caoym.jjvm.opcode.JvmOpcodeClass.clinit(JvmOpcodeClass.java:87)
	at org.caoym.jjvm.opcode.JvmOpcodeMethod.call(JvmOpcodeMethod.java:62)
	at org.caoym.jjvm.VirtualMachine.run(VirtualMachine.java:44)
	at org.caoym.jjvm.JJvm.main(JJvm.java:28)
