### ISSUE TITLE
Run Error:Exception in thread "main" java.lang.InternalError: The opcode arraylength Not Impl

### ISSUE THREAD

**Issue by okman1214** [caoym/jjvm#4]
/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:61115,suspend=y,server=n -javaagent:/Users/gaolianchi/Library/Caches/IntelliJIdea2018.2/captureAgent/debugger-agent.jar=file:/private/var/folders/ly/f_9whgj13kb6j8mq3wtwh984gss97k/T/capture.props -Dfile.encoding=UTF-8 -classpath "/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/lib/tools.jar:/Users/gaolianchi/workspace/jjvm/target/classes:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar" org.caoym.jjvm.JJvm /Users/gaolianchi/workspace/jjvm/target/classes org.caoym.jjvm.JJvm com.msdnfaq.jvm.test.Test
Connected to the target VM, address: '127.0.0.1:61115', transport: 'socket'
Exception in thread "main" java.lang.InternalError: The opcode arraylength Not Impl
	at org.caoym.jjvm.opcode.OpcodeRout.valueOf(OpcodeRout.java:460)
	at org.caoym.jjvm.opcode.BytecodeInterpreter.parseCodes(BytecodeInterpreter.java:57)
	at org.caoym.jjvm.opcode.JvmOpcodeMethod.<init>(JvmOpcodeMethod.java:24)
	at org.caoym.jjvm.opcode.JvmOpcodeClass.<init>(JvmOpcodeClass.java:49)
	at org.caoym.jjvm.opcode.JvmOpcodeClass.read(JvmOpcodeClass.java:30)
	at org.caoym.jjvm.JvmDefaultClassLoader.loadClass(JvmDefaultClassLoader.java:33)
	at org.caoym.jjvm.VirtualMachine.getClass(VirtualMachine.java:50)
	at org.caoym.jjvm.VirtualMachine.run(VirtualMachine.java:38)
	at org.caoym.jjvm.JJvm.main(JJvm.java:18)
Disconnected from the target VM, address: '127.0.0.1:61115', transport: 'socket'

Process finished with exit code 1

**Comment by okman1214** [comment]
@caoym    有空帮忙看看嘛，The opcode arraylength Not Impl  没有实现

**Comment by caoym** [comment]
jjvm只实现了很少的一部分opcode，`arraylength`没有实现。可能是你尝试让jjvm运行的代码，依赖了`arraylength`
