### ISSUE TITLE
执行sample2报错

### ISSUE THREAD

**Issue by huangwei2013** [caoym/jjvm#7]
`执行sample2报错如下，sample1可正常执行
> org/caoym/samples/sample2/Main.<clinit>@1:DUP
> org/caoym/samples/sample2/Main.<clinit>@2:LDC
> org/caoym/samples/sample2/Main.<clinit>@3:INVOKESPECIAL
> org/caoym/samples/sample2/Speaker.<init>@0:ALOAD_0
> org/caoym/samples/sample2/Speaker.<init>@1:INVOKESPECIAL
> org/caoym/samples/sample2/Speaker.<init>@2:ALOAD_0
> org/caoym/samples/sample2/Speaker.<init>@3:LDC
> org/caoym/samples/sample2/Speaker.<init>@4:PUTFIELD
> org/caoym/samples/sample2/Speaker.<init>@5:ALOAD_0
> org/caoym/samples/sample2/Speaker.<init>@6:ALOAD_1
> org/caoym/samples/sample2/Speaker.<init>@7:PUTFIELD
> org/caoym/samples/sample2/Speaker.<init>@8:RETURN
> org/caoym/samples/sample2/Main.<clinit>@4:PUTSTATIC
> org/caoym/samples/sample2/Main.<clinit>@5:RETURN
> org/caoym/samples/sample2/Main.main@0:GETSTATIC
> org/caoym/samples/sample2/Main.main@1:ALOAD_0
> org/caoym/samples/sample2/Main.main@2:ICONST_0
> org/caoym/samples/sample2/Main.main@3:AALOAD
java.lang.ArrayIndexOutOfBoundsException: 0
	at org.caoym.jjvm.opcode.OpcodeRout$31.invoke(OpcodeRout.java:325)
	at org.caoym.jjvm.opcode.BytecodeInterpreter$1.invoke(BytecodeInterpreter.java:64)
	at org.caoym.jjvm.opcode.BytecodeInterpreter.run(BytecodeInterpreter.java:50)
	at org.caoym.jjvm.opcode.JvmOpcodeMethod.call(JvmOpcodeMethod.java:64)
	at org.caoym.jjvm.opcode.JvmOpcodeClass.clinit(JvmOpcodeClass.java:88)
	at org.caoym.jjvm.opcode.JvmOpcodeMethod.call(JvmOpcodeMethod.java:63)
	at org.caoym.jjvm.VirtualMachine.run(VirtualMachine.java:44)
	at org.caoym.jjvm.JJvm.main(JJvm.java:18)
`

**Comment by huangwei2013** [comment]
以上问题发现是 OpcodeRout.java 中 AALOAD 指令 中 arrayRef 长度为0导致
增加保护处理（不确定是否合适）
```OpcodeRout.java

    AALOAD(Constants.AALOAD){
        @Override
        public void invoke(Env env, StackFrame frame, byte[] operands) throws Exception {
            int index = (int) frame.getOperandStack().pop();
            Object[] arrayRef = (Object[]) frame.getOperandStack().pop();
            if( null != arrayRef && arrayRef.length > 0){
                frame.getOperandStack().push(arrayRef[index]);
            }
        }
    },
```
程序进展到（仍有报错）
```
...
> org/jvm/samples/sample2/Speaker.helloTo@7:LDC
> org/jvm/samples/sample2/Speaker.helloTo@8:INVOKEVIRTUAL
> org/jvm/samples/sample2/Speaker.helloTo@9:ALOAD_1
> org/jvm/samples/sample2/Speaker.helloTo@10:INVOKEVIRTUAL
sun.reflect.generics.reflectiveObjects.NotImplementedException
	at org.jvm.jjvm.natives.JvmNativeObject.getSuper(JvmNativeObject.java:30)
	at org.jvm.jjvm.opcode.OpcodeRout$7.invoke(OpcodeRout.java:108)
	at org.jvm.jjvm.opcode.OpcodeRout$9.invoke(OpcodeRout.java:130)
	at org.jvm.jjvm.opcode.BytecodeInterpreter$1.invoke(BytecodeInterpreter.java:64)
	at org.jvm.jjvm.opcode.BytecodeInterpreter.run(BytecodeInterpreter.java:50)
	at org.jvm.jjvm.opcode.JvmOpcodeMethod.call(JvmOpcodeMethod.java:64)
	at org.jvm.jjvm.opcode.JvmOpcodeClass.clinit(JvmOpcodeClass.java:88)
	at org.jvm.jjvm.opcode.JvmOpcodeMethod.call(JvmOpcodeMethod.java:63)
	at org.jvm.jjvm.VirtualMachine.run(VirtualMachine.java:44)
	at org.jvm.jjvm.JJvm.main(JJvm.java:18)

```
getSuper() 接口的加载有问题？

代码提交到 https://github.com/huangwei2013/jjvm

**Comment by huangwei2013** [comment]
发现是个乌龙，执行sample2没有加上入参，导致出现这些错误。。。
